### ISSUE TITLE
Binary Length incorrect

### ISSUE THREAD

**Issue by hammyau** [genevaers/wb#34]
COBOL copybook converter calculates a wrong value for  the following.
05  RH-FILE-ID                       PIC S9(08) COMP.

Generates a length of 2 not 4.

See https://www.ibm.com/docs/en/i/7.4?topic=clause-computational-5-comp-5-phrase-binary

However, should COMP always be treated as Binary...or PACKED?
https://www.ibm.com/docs/en/i/7.4?topic=clause-computational-comp-phrase

**Comment by rhness** [comment]
The web links you reference here are invalid for our purposes.  They deal with the IBM i (midrange computer) product series as opposed to the IBM Z (mainframe computer) product series.  The correct link for us is: 
https://www.ibm.com/docs/en/cobol-zos/6.3?topic=clause-computational-items

The copybook converter should always treat COMP, COMP-4, and COMP-5 as BINARY. 
It should always treat COMP-3 as PACKED.  
It won't support COMP-1 and COMP-2, as GenevaERS does not (currently) support floating point items.
